blog/urls.py
from django.urls import path

from . import views

app_name = 'home'
 
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('tag/<slug:slug>/', views.Home.as_view(), name='type'),
    path('post/<slug:slug>/', views.single_post, name='single_post'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from blog.admin import admin_site

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('admin/', admin_site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from autoslug import AutoSlugField
from django.db import models
from django.template.defaultfilters import truncatechars
from django.utils.html import format_html


class Tag(models.Model):
    name = models.CharField(max_length=30, verbose_name='Nombre')
    slug = AutoSlugField(populate_from='name', unique=True)

    class Meta:
        ordering = ['name', 'id']
        verbose_name = 'Etiqueta'

    def __str__(self):
        return '{}, {}'.format(self.name, self.slug)

    def get_btn(self):
        return format_html('<a class="button" href="#">Ver</a>')
    get_btn.short_description = 'Ver'

    def get_posts(self):
        return self.post_set.filter(draft=False).count()

class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='Titulo')
    content = models.TextField(max_length=300, verbose_name='Contenido')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Ultima modificación')
    draft = models.BooleanField(default=True, verbose_name='Borrador')
    publish_date = models.DateField(verbose_name='Fecha de publicación')
    tags = models.ManyToManyField(Tag, verbose_name='Etiquetas')
    slug = AutoSlugField(populate_from='title', unique=True)
    image = models.ImageField(verbose_name='Imagen', upload_to='blog/uploads/')

    class Meta:
        ordering = ['-created_date', 'title']
        verbose_name = 'Publicación'
        verbose_name_plural = 'Publicaciones'

    def image_preview(self):
        if self.image:
            return format_html('<img src="{}" width="100" height="100" />'.format(self.image.url))
        return ""
    image_preview.short_description = 'Imagen'

    def short_content(self):
        return truncatechars(self.content, 100)
    short_content.short_description = 'Contenido'

    def get_btn(self):
        return format_html('<a class="button" href="#">Ver</a>')
    get_btn.short_description = 'Ver'

    def get_tags(self):
        return ", ".join([p.name for p in self.tags.all()])
    get_tags.short_description = 'Etiquetas'

blog/views.py
from digg_paginator import DiggPaginator
from django.contrib.auth import authenticate
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic.list import ListView

from .models import Post, Tag


class Home(ListView):
    model = Post
    paginate_by = 3
    template_name = 'blog.html'
    paginator_class = DiggPaginator

    def get_queryset(self, *args, **kwargs):
        qs = super(Home, self).get_queryset(*args, **kwargs).exclude(draft=True)

        # Este try sirve para que no se repita mas de 1 vez los resultados?
        try:
            qs = qs.filter(slug__exact=self.kwargs['slug'])
        except:
            pass

        if 'q' in self.request.GET:
            query = self.request.GET['q']
            qs = (qs.filter(title__icontains=query)).distinct()
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(Home, self).get_context_data(*args, **kwargs)
        if 'q' in self.request.GET:
            context['q'] = self.request.GET['q']
            context['title'] = 'Resultados de la busqueda'

        try:
            context['slug'] = self.kwargs['slug']
        except:
            context['slug'] = None

        if not context['slug'] is None:
            slug = get_object_or_404(Tag.objects.filter(slug__exact=self.kwargs['slug']))
            context['tags'] = Post.objects.filter(tags=slug)
        return context


def single_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render(request, 'post.html', locals())


def login(request):
    if request.user.is_authenticated:
        return redirect('/dashboard')
    else:
        form = AuthenticationForm()
        if request.method == "POST":
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(username=username, password=password)
                if user is not None:
                    do_login(request, user)
                    return redirect('/dashboard')
            else:
                message = 'El usuario no existe o los datos son incorrectos'
    return render(request, 'login.html', locals())


def logout(request):
    if request.user.is_authenticated is False:
        return redirect('/login')
    do_logout(request)
    return redirect('/')

blog/templates/tags/sidebar.html
          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Buscador</h5>
            <div class="card-body">
              <form method="GET" action="/">
              <div class="input-group">
                  <input type="search" class="form-control" placeholder="Titulo del post" name="q" value="{{ q }}">
                  <span class="input-group-btn">
                    <button class="btn btn-secondary" type="submit">Buscar</button>
                  </span>
                </div>
              </form>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Posts totales ({{ total_post }})</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    {% for object in object_list %}
                    <li>
                      <a href="{% url 'home:type' slug=object.slug %}">{{ object.name|capfirst }}</a>
                      {#<span class="float-right">({{ object.post_set.all|length }})</span>#}
                      <span class="float-right">({{ object.get_posts }})</span>
                    </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Widget de ejemplo</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
            </div>
          </div>
        </div>
      </div>
    </div>