blog/urls.py
from django.urls import path

from . import views

app_name = 'home'
 
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('tag/<slug:slug>/', views.Home.as_view(), name='type'),
    path('post/<slug:slug>/', views.single_post, name='single_post'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'admin'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('getaction', views.get_action, name='get_action'),

    path('posts/', views.Posts.as_view(), name='posts'),
    path('posts/nuevo/', views.new_post, name='new_post'),
    path('posts/editar/<int:id>/', views.edit_post, name='edit_post'),
    path('posts/<int:id>/', views.Posts.as_view(), name='delete_post'),

    path('tags/', views.Tags.as_view(), name='tags'),
    path('tags/nuevo', views.new_tag, name='new_tag'),
    path('tags/editar/<int:id>/', views.edit_tag, name='edit_tag'),
    path('tags/borrar/<int:id>/', views.delete_tag, name='delete_tag'),
]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from blog.admin import admin_site

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('admin/', admin_site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/forms.py
from django import forms

from blog.models import Post, Tag


class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class TagForm(forms.ModelForm):

    class Meta():
        model = Tag
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TagForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

dashboard/views.py
import json

from digg_paginator import DiggPaginator
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from django.http import JsonResponse, HttpResponse

from blog.models import Post, Tag

from .forms import PostForm, TagForm

# Create your views here.


@method_decorator(login_required, name='dispatch')
class Posts(ListView):
    model = Post
    paginate_by = 5
    template_name = 'postsView.html'
    paginator_class = DiggPaginator

    def get_queryset(self, *args, **kwargs):
        qs = super(Posts, self).get_queryset(*args, **kwargs)
        if 'q' in self.request.GET:
            query = self.request.GET['q']
            qs = (qs.filter(title__icontains=query)).distinct()
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(Posts, self).get_context_data(*args, **kwargs)
        if 'q' in self.request.GET:
            context['q'] = self.request.GET['q']
            context['title'] = 'Resultados de la busqueda'
        return context

    # Forbideen 403  
    def delete_post(request, id):
        if request.user.is_authenticated is False:
            return redirect('/login')
        object = get_object_or_404(Post, id=id)
        if request.method == 'POST':
            object.delete()
        
        return JsonResponse(
            {
                'content': {
                    'message': 'El post se ha borrado con exito',
                }
            }
        )


@method_decorator(login_required, name='dispatch')
class Tags(ListView):
    model = Tag
    paginate_by = 5
    template_name = 'tagsView.html'
    paginator_class = DiggPaginator

    def get_queryset(self, *args, **kwargs):
        qs = super(Tags, self).get_queryset(*args, **kwargs)
        if 'q' in self.request.GET:
            query = self.request.GET['q']
            qs = (qs.filter(name__icontains=query)).distinct()
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(Tags, self).get_context_data(*args, **kwargs)
        if 'q' in self.request.GET:
            context['q'] = self.request.GET['q']
            context['title'] = 'Resultados de la busqueda'
        return context


def dashboard(request):
    if request.user.is_authenticated:
        total_post = Post.objects.all().count()
        total_tag = Tag.objects.all().count()
        return render(request, 'dashboardView.html', locals())
    return redirect('/login')

def get_action(request):
    object_list = Post.objects.all()
    ajax_response = True
    to_json = {
        'ajax_response': ajax_response
    }
    user_list = []
    for post in object_list:
        result = {
            'id': post.id,
            'title': post.title,
            'content': post.content,
        }
        user_list.append(result)
    # print(user_list)
    json_dump = json.dumps(
        {
            'to_json': True,
            'user_list': user_list
        },
        indent=3
    )
    print(json_dump)
    return HttpResponse(
        json_dump,
        content_type='application/json'
    )


def new_post(request):
    if request.user.is_authenticated is False:
        return redirect('/login')
    title = 'Agregar una publicación'
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            save_form = form.save()
            save_form.save()
            message = 'La publicación ha sido publicada correctamente'
    form = PostForm()
    return render(request, 'dashboardForm.html', locals())


def edit_post(request, id):
    if request.user.is_authenticated is False:
        return redirect('/login')
    title = 'Editar una publicación'
    object = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=object)
        if form.is_valid():
            save_form = form.save()
            message = 'La publicación ha sido modificada correctamente'
    form = PostForm(instance=object)
    return render(request, 'dashboardForm.html', locals())

"""
def delete_post(request, id):
    if request.user.is_authenticated is False:
        return redirect('/login')
    object = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        object.delete()
        message = 'La publicación se ha borrado con exito'
    form = PostForm()
    return render(request, 'dashboardForm.html', locals())
"""


def new_tag(request):
    if request.user.is_authenticated is False:
        return redirect('/login')
    title = 'Agregar una etiqueta'
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            save_form = form.save()
            save_form.save()
            message = 'La etiqueta ha sido creada correctamente'
    form = TagForm()
    return render(request, 'dashboardForm.html', locals())


def edit_tag(request, id):
    if request.user.is_authenticated is False:
        return redirect('/login')
    title = 'Editar una etiqueta'
    object = get_object_or_404(Tag, id=id)
    if request.method == 'POST':
        form = TagForm(request.POST, request.FILES, instance=object)
        if form.is_valid():
            save_form = form.save()
            message = 'La etiqueta ha sido modificado correctamente'
    form = TagForm(instance=object)
    return render(request, 'dashboardForm.html', locals())


def delete_tag(request, id):
    if request.user.is_authenticated is False:
        return redirect('/login')
    object = get_object_or_404(Tag, id=id)
    if request.method == 'POST':
        object.delete()
        message = 'La etiqueta se ha eliminado correctamente'
    form = TagForm()
    return render(request, 'dashboardForm.html', locals())

dashboard/templates/dashboardForm.html
{%extends 'base_dashboard.html' %}

{% block content %}

<div class="row">
  <div class="col-3"></div>

  <div class="col-6">
    {% if message %}
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Todo correcto!</h4>
      <p>{{ message }}</p>
      <hr>
      {% if 'etiqueta' in message %}
      <p class="mb-0">Pulsa <a href="{% url 'dashboard:tags' %}">aqui para regresar</a></p>
      {% elif 'publicación' in message %}
      <p class="mb-0">Pulsa <a href="{% url 'dashboard:posts' %}">aqui para regresar</a></p>
      {% else %}
      <p class="mb-0">Al parecer hubo un error al generar el link de regreso</a></p>
      {% endif %}
    </div>
    {% else %}

    <h2>{{ title }}</h2>
    <br>
    <form id="Form" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}

      <div class="form-group">
      <label for="">{{ field.label }}</label>
      {{ field }}
      </div>
      {% endfor %}

      <div class="form-group">

        {% if 'etiqueta' in title %}
        <a class="btn btn-danger" href="{% url 'dashboard:tags' %}">Cancelar</a>
        {% elif 'publicación' in title %}
        <a class="btn btn-danger" href="{% url 'dashboard:posts' %}">Cancelar</a>
        {% else %}
        <p class="mb-0">Al parecer hubo un error</a></p>
        {% endif %}

        <button type="submit" class="btn btn-success">Guardar</button>
      </div>
    </form>
    {% endif %}
  </div>

  <div class="col-3"></div>
</div>

{% endblock %}

dashboard/templates/dashboardView.html
{%extends 'base_dashboard.html' %}

{% block content %}

  <h1> Centro de control </h1>

  <a href="{% url 'blog:home' %}" class="btn btn-lg btn-primary">Ir al sitio</a>
  <br>

  <h2>Todos las publicaciones creadas:  {{ total_post }}</h2>
  <a href="" class="btn btn-success">Ver publicaciones</a>
  <h2>Todos las etiquetas creadas:  {{ total_tag }}</h2>
  <a href="{% url 'dashboard:tags' %}" class="btn btn-success">Ver etiquetas</a>

  <h2>Obtener respuesta del servidor</h2>
  <button class="btn btn-primary" onclick=" getAction() "> Obtener respuesta </button>
  <br>
  <!--<i class="fas fa-spinner fa-pulse"></i>-->

  <div id="contentPost"></div>

  {% block js %}

  <script>

    function getAction() {

      $("#contentPost").empty();
      $('#contentPost').html('<div>Espere un momento... <i class="fas fa-spinner fa-pulse"></i></div>');

        var req = $.ajax({
          method: "GET",
          url: "{% url 'dashboard:get_action' %}",
        });

      req.done(function(data){
        $("#contentPost").empty();
        if (data.to_json.ajax_response === false){
          alert("Ha ocurrido un error al conectarse al servidor")
        }else{

          //alert("Respuesta recibida");
          var get_data = data.user_list;
          for(var i = 0; i < get_data.length; i++) {

          $("#contentPost").append(`
            <div class="row">
              <div class="col-12">`+get_data[i].id+`</div>
                </div>
              <div class="row mb-5">
                <div class="col-8">`+get_data[i].title+`</div>
                <div class="col-4">`+get_data[i].content+`</div>
                </div>
                `);
              }
            }
      });
      req.fail(function(jqXHR, textStatus){
        alert("Error de conexión")
      });
    }
  </script>
  {% endblock %}

{% endblock %}

dashboard/templates/postsView.html
{%extends 'base_dashboard.html' %}
{% load static %}
{% block content %}

<div class="row">
  <div class="col-10"><h2>Publicaciones creadas</h2></div>
  <div class="col-2"><a href="{% url 'dashboard:new_post' %}" class="btn btn-success">Agregar Post</a></div>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        {% if object_list|length >= 1 %}
        <thead>
          <tr>
            <th>Id</th>
            <th>Imagen</th>
            <th>Titulo</th>
            <th>Contenido</th>
            <th>Etiquetas</th>
            <th>Opciones</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          <tr>
            <td>{{ object.id }}</td>
            <td><a href="{% url 'dashboard:edit_post' id=object.id %}">{{ object.image_preview }}</a></td>
            <td><a href="{% url 'dashboard:edit_post' id=object.id %}">{{ object.title }}</a></td>
            <td>{{ object.short_content }}</td>
            <td>{{ object.get_tags }}</td>
            {% if object.draft != True %}
            <td><a href="{% url 'blog:single_post' slug=object.slug %}" class="btn btn-primary">Ver en el sitio</a></td>
            {% else %}
            <td><a href="#" class="btn btn-secondary disabled" >Ver en el sitio</a><br><small>Borrador</small></td>
            {% endif %}

            {# <form id="id_delete_post" action="{% url 'dashboard:delete_post' id=object.id %}" method="POST"> #}

            <form id="id_delete_post" data-post-url="{% url 'dashboard:delete_post' id=object.id %}" method="POST">
              {% csrf_token %}
              <td><input type="submit" class="btn btn-danger" value="Borrar"></td>
            </form>
          </tr>
          {% endfor %}
        </tbody>
        
        {% else %}
        
        <thead>
          <tr>{{ title }}</tr>
        </thead>
        <tbody>
          <tr>
            <td>No se han encontrado registros</td>
          </tr>
        </tbody>
        
        {% endif %}
        
      </table>
    </div>
  </div>
</div>

{% include 'includes/pagination.html' %}

{% block js %}

<script>
  $(function() {
    'use estrict';

    $('#id_delete_post').on('submit', function() {

      $.ajax({
        url : "{% url 'dashboard:delete_post'  %}",
        method : "POST",
        data: "id=object.id",
        processData: false,
        contentType: false,
        success:function(response){
          var message = response.content.message;
          alert(message);
        },

      })
      //alert("ENVIADO");
      return false;
    });
  });
</script>

{% endblock %}

{% endblock %}

dashboard/templates/tagsView.html
{%extends 'base_dashboard.html' %}

{% block content %}

<div class="row">
  <div class="col-10"><h2>Etiquetas creadas</h2></div>
  <div class="col-2"><a href="{% url 'dashboard:new_tag' %}" class="btn btn-success">Agregar Etiqueta</a></div>
</div>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        {% if object_list|length >= 1 %}
        <thead>
          <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Slug</th>
            <th>Opciones</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          <tr>
            <td><a href="{% url 'dashboard:edit_tag' id=object.id %}">{{ object.id }}</a></td>
            <td><a href="{% url 'dashboard:edit_tag' id=object.id %}">{{ object.name }}</a></td>
            <td>{{ object.slug }}</td>
            <form action="{% url 'dashboard:delete_tag' id=object.id %}" method="POST">
              {% csrf_token %}
              <td><input type="submit" class="btn btn-danger" value="Borrar"></td>
            </form>
          </tr>
          {% endfor %}
        </tbody>
        {% else %}
        
        <thead>
          <tr>Error</tr>
        </thead>
        <tbody>
          <tr>
            <td>No se han encontrado registros</td>
          </tr>
        </tbody>
        
        {% endif %}
      </table>
    </div>
  </div>
</div>

{% include 'includes/pagination.html' %}

{% endblock %}